### ISSUE TITLE
Google sheet to import hourly revenue

### ISSUE THREAD

**Issue by mvhaen** [Onlinewerkrooster/strobbo-google-app-scripts#2]
- As a user I can configure an API key
- As a user I can enter the hourly revenue for a workspace for 1 business day and upload it (validations will happen through the API).
  - The user needs to explicitly enter the business day
  - The user needs to enter the export code of the workspace (just as in the API)
 
Use the `revenue/hourly` endpoint to upload the revenue.

I’ve prepared a google sheet already with the layout I was thinking of, but feel free to change it: https://docs.google.com/spreadsheets/d/1I7QcHPZYdCCO7I-jw8Tbin7SDHv3ZCObNNIN8OBkrr4/edit

Question from my side, how difficult would it be to upload for multiple days and multiple workspaces at once? We would need to do multiple calls, but if that would work it would be very nice. The above is the bare minimum.

**Comment by mvhaen** [comment]
@TimVee can you have a look at this?

**Comment by TimVee** [comment]
This can be tested. Do you want this script in this repo?

**Comment by mvhaen** [comment]
yep, best to add it here.

**Comment by mvhaen** [comment]
I've asked for a DEV_KFCVL environment to test this.

**Comment by mvhaen** [comment]
@TimVee did you by any chance test if the data that was uploaded ended up in the SalesOverview table?

I'm testing this for a new copy of KFCVL and don't see any of the data ending up in the database.

**Comment by mvhaen** [comment]
@TimVee never mind, I made a mistake. It's working as I expected.
