### ISSUE TITLE
Add hourly revenue to reporting google sheet and excel file

### ISSUE THREAD

**Issue by mvhaen** [Onlinewerkrooster/strobbo-google-app-scripts#5]
Modify the following files and add support for the hourly revenue API:

- <https://docs.google.com/spreadsheets/d/1WZOX8tNkUol64bUorc97iI157-2HH4p2_4tGPin50Fo/edit?usp=sharing>
- <https://sd-my.sharepoint.com/:x:/g/personal/michael_voorhaen_sdworx_com/EVGeeemZGTtIid3OPk4oRmoBHXBpGdgQ0JPsC_304hJm4Q?email=tim.veestraeten%40strobbo.com&e=VkvVmb>

**Comment by TimVee** [comment]
[Reporting - v1.1.xlsx](https://github.com/Onlinewerkrooster/strobbo-google-app-scripts/files/12274577/Reporting.-.v1.1.xlsx)

**Comment by mvhaen** [comment]
Looks good, updated the confluence documentation to point to the new versions.

**Comment by mvhaen** [comment]
Looks good, updated the confluence documentation to point to the new versions.
